### ISSUE TITLE
Bot issues (no claim, desconfigured claim reset and same thing with Kakera)

### ISSUE THREAD

**Issue by KrevoLCN** [chiyadev/MudaeFarm#111] opened 2020-04-24 16:57 UTC
Hello, i have this problem:

![image](https://user-images.githubusercontent.com/20275034/80237341-325a2500-8622-11ea-9455-8cb58ba3a640.png)

The bot no claim, and in the $tu status update says this:
![image](https://user-images.githubusercontent.com/20275034/80237539-8238ec00-8622-11ea-8902-c057ea27c50b.png)
True status:
![image](https://user-images.githubusercontent.com/20275034/80237629-ab597c80-8622-11ea-82fe-36180e571297.png)

Says: no claim, and claim reset in 31-12-9999 (lmao)
same thing with Kakera, i only get purple kakera (free)
Any way to fix it?

**Comment by phosphene47** [comment] 2020-04-24 17:25
Thanks for providing detailed information. MudaeFarm does not support languages other than English at the moment. As this is a duplicate of https://github.com/chiyadev/MudaeFarm/issues/67, I will close this issue.

**Closed by phosphene47** 2020-04-24 17:25 UTC
Labels: invalid

**Comment by KrevoLCN** [comment] 2020-04-25 23:57
> Thanks for providing detailed information. MudaeFarm does not support languages other than English at the moment. As this is a duplicate of #67, I will close this issue.

Is there a way that we can change the keywords?
As I read in post # 67, use keywords like Claim, Daily, etc.
Some way?

**Comment by phosphene47** [comment] 2020-04-26 06:56
For now, this is not possible. If you are desperate, you can edit [this file](https://github.com/chiyadev/MudaeFarm/blob/master/MudaeFarm/TimersUpParser.cs) and compile the bot yourself, assuming you can write C#.
