### ISSUE TITLE
Bot still claiming color kakera not mentioned in #information as well as during cooldown when ignore_cooldown false.

### ISSUE THREAD

**Issue by joshoea** [chiyadev/MudaeFarm#160] opened 2020-06-20 04:51 UTC
I specifically removed "blue, and purple" kakera from #information. However, the bot tried to claim blue kakera. This happened during cooldown as well when it shouldn't be as ignore_cooldown is false?! For me none of the ignore_cooldowns have been working and now the kakera color choosing isnt working.
![Screenshot (221)](https://user-images.githubusercontent.com/67028136/85192324-f1c00600-b276-11ea-8508-ad3d18aee8d0.png)
![Screenshot (220)_LI](https://user-images.githubusercontent.com/67028136/85192332-f84e7d80-b276-11ea-9db4-fc62cebcfa88.jpg)

**Comment by phosphene47** [comment] 2020-06-20 11:49
Duplicate of #128.

**Closed by phosphene47** 2020-06-20 11:49 UTC
