### ISSUE TITLE
Issues with the logging accounts

### ISSUE THREAD

**Issue by KosakiAjami** [chiyadev/MudaeFarm#100] opened 2020-02-27 21:23 UTC
Hello, I have a problem with MudaeFarm when I choose the profile on The Interface , I have the impression that the bot connects to the account and disconnects but does not create a discord server as it is supposed to do.
[log.txt](https://github.com/chiyadev/MudaeFarm/files/4264110/log.txt)
If you can add me in discord Saikuo#8037. Thanks :D

**Comment by phosphene47** [comment] 2020-02-28 11:30
I cannot reproduce this issue at all. Can you post the log file again with [verbose logging](https://github.com/chiyadev/MudaeFarm/issues/55#issuecomment-541301349)?

```
"C:\Program Files\JetBrains\JetBrains Rider 2019.3.1\lib\ReSharperHost\JetBrains.Debugger.Worker64c.exe" --mode=client --frontend-port=49656 "--plugins=C:\Program Files\JetBrains\JetBrains Rider 2019.3.1\plugins\rider-unity\dotnetDebuggerWorker"
[warn] [10:24:45] MudaeFarm v3.1.1 by chiya.dev
[info] [10:24:45] Profiles loaded from: C:\Users\User\AppData\Local\MudaeFarm\profiles.json

Profiles:
  - testo

Choose profile: testo
[info] [10:24:46] Selected profile: testo
[info] [10:24:46] Discord.Net v2.1.1 (API v6)
[info] [10:24:47] Connecting
[warn] [10:24:48] Unknown Dispatch (SESSIONS_REPLACE)
[warn] [10:24:48] Logged in as: tetseettet (682910695158841345)
[info] [10:24:48] Connected
[warn] [10:24:48] Initializing a new configuration server. This may take a while...
[info] [10:24:48] Ready
[dbug] [10:24:50] Channel created: '#information' - 'MudaeFarm: **682910695158841345**
[dbug] [10:24:50] Profile: **testo**
[dbug] [10:24:50] Version: **v3.1.1**'
[dbug] [10:24:52] Channel created: '#wished-characters' - 'Configure your character wishlist here. Wildcards characters are supported. Names are *case-insensitive*.'
[warn] [10:24:52] Failed to resume previous session
[dbug] [10:24:53] Channel created: '#wished-anime' - 'Configure your anime wishlist here. Wildcards characters are supported. Names are *case-insensitive*.'
[warn] [10:24:53] Failed to resume previous session
[info] [10:24:53] Ready
[warn] [10:24:53] Unknown Dispatch (SESSIONS_REPLACE)
[dbug] [10:24:54] Channel created: '#bot-channels' - 'Configure channels to enable MudaeFarm autorolling/claiming by sending the __channel ID__.'
[dbug] [10:24:54] Channel created: '#claim-replies' - 'Configure automatic reply messages when you claim a character. One message is randomly selected. Refer to https://github.com/chiyadev/MudaeFarm for advanced templating.'
[dbug] [10:24:55] Channel created: '#wishlist-users' - 'Configure wishlists of other users to be claimed by sending the __user ID__.'
[info] [10:24:57] Configuration channel '#information' reloaded in 1.38s.
[info] [10:24:57] Configuration channel '#wished-characters' reloaded in 277.70ms.
[info] [10:24:57] Configuration channel '#wished-anime' reloaded in 251.32ms.
[info] [10:24:58] Configuration channel '#bot-channels' reloaded in 290.61ms.
[info] [10:24:58] Configuration channel '#claim-replies' reloaded in 255.23ms.
[info] [10:24:58] Configuration channel '#wishlist-users' reloaded in 269.59ms.
[info] [10:24:58] Configuration loaded in 9.95s.
[warn] [10:24:58] Waiting for connection to stabilize...
[warn] [10:25:01] Failed to resume previous session
[info] [10:25:01] Ready
[warn] [10:25:01] Unknown Dispatch (SESSIONS_REPLACE)
[dbug] [10:25:01] patience...
[dbug] [10:25:02] nearly there... 3
[dbug] [10:25:05] nearly there... 2
[dbug] [10:25:08] nearly there... 1
[info] [10:25:10] Connected stabilized in 11.72s.
[info] [10:25:41] Left MudaeFarm (testo)
[warn] [10:25:43] Unknown Dispatch (SESSIONS_REPLACE)

Process finished with exit code 0.
```

**Comment by KosakiAjami** [comment] 2020-02-28 19:10
Do you can give me an copy of your profiles.json file please without the token because I don't how to use this. Please

**Comment by phosphene47** [comment] 2020-02-28 20:51
Your profiles.json should look something like this.

```
{
  "default": ""
}
```

As I said, can you post the log file again with [verbose logging](https://github.com/chiyadev/MudaeFarm/issues/55#issuecomment-541301349)? I can't help you otherwise.

**Comment by KosakiAjami** [comment] 2020-02-29 13:06
Yes but i don't find the good token i use your technic but that's wrong how to surely find his token.

**Comment by KosakiAjami** [comment] 2020-02-29 14:24
![unknown](https://user-images.githubusercontent.com/61561851/75609294-991dff00-5b07-11ea-8f08-be1832b10f07.png)

**Comment by KosakiAjami** [comment] 2020-02-29 16:12
Can you add Saikuo#8037 in discord it's more easy to comunicate. Thanks

**Comment by phosphene47** [comment] 2020-03-02 20:45
This looks like a duplicate of https://github.com/chiyadev/MudaeFarm/issues/82, so I am closing this issue. There has been much discussion about this but no known solution yet.

**Closed by phosphene47** 2020-03-02 20:45 UTC
Labels: bug, invalid
