### ISSUE TITLE
Claim characters only when they have a certain amount of kakera

### ISSUE THREAD

**Issue by KosakiAjami** [chiyadev/MudaeFarm#107] opened 2020-03-21 20:18 UTC
Add a feature that claims characters from a number of kakeras. For example, the bot claim of all the characters who are worth at least 500 ka (and being able to modify this value)

**Comment by phosphene47** [comment] 2020-05-31 23:42
This is a duplicate of https://github.com/chiyadev/MudaeFarm/issues/38. No progress as of yet.

**Closed by phosphene47** 2020-05-31 23:42 UTC
Labels: enhancement, help wanted
