### ISSUE TITLE
MudaeFarm dont open

### ISSUE THREAD

**Issue by edu7213** [chiyadev/MudaeFarm#163] opened 2020-06-20 17:58 UTC
![Screenshot_4](https://user-images.githubusercontent.com/66887277/85208390-64c48d80-b306-11ea-8b62-f242e4984889.png)
i have this version that i dont know witch one are, and i woke up today and it just dont open

**Comment by phosphene47** [comment] 2020-06-20 18:02
In file explorer, can you try entering `cmd` in the address bar, and then enter the text `./MudaeFarm.exe --verbose`?

**Comment by edu7213** [comment] 2020-06-20 18:19
i dont understand what i need to comand, i tryed to start the exe, i tried to copy what you write, i tried to start what you write, the only result was when i put start and the result was that the archive doesnt exist

**Comment by phosphene47** [comment] 2020-06-21 05:01
Enter `cmd` in the address bar.

![image](https://user-images.githubusercontent.com/27663662/85217054-db798d80-b3cf-11ea-966b-c0f006bfa3de.png)

Enter `MudaeFarm.exe --verbose`.

![image](https://user-images.githubusercontent.com/27663662/85217067-0368f100-b3d0-11ea-95a9-aacfc612e994.png)

**Comment by joshoea** [comment] 2020-06-21 09:05
The application to execute does not exist: 'C:\Users\jyang\Desktop\MudaeFarm\MudaeFarm.dll'. is what i got

**Comment by joshoea** [comment] 2020-06-22 20:43
The problem is probably that windows security stopped it from working. you need to go into windows security and allow the "threat" and if that doesn't work redownload it. It happened to me. I'm running 3 devices and I had to redownload it on one of them

**Comment by phosphene47** [comment] 2020-06-25 09:08
Duplicate of #165.

**Closed by phosphene47** 2020-06-25 09:08 UTC
Labels: question
