### ISSUE TITLE
A ReactionAdded handler is blocking the gateway task

### ISSUE THREAD

**Issue by Jaminator827** [chiyadev/MudaeFarm#124] opened 2020-05-25 02:55 UTC
This stops the bot from doing anything at all and sometimes fixes itself when restarting the program

**Comment by phosphene47** [comment] 2020-05-25 18:31
Due to the lack of information I'm going to guess that this issue is a duplicate of https://github.com/chiyadev/MudaeFarm/issues/92 or https://github.com/chiyadev/MudaeFarm/issues/55. I have not been able to find the cause of these issues yet.

**Closed by phosphene47** 2020-05-25 18:31 UTC
