### ISSUE TITLE
Sorting auto claims by kakera value

### ISSUE THREAD

**Issue by Yakuza069** [chiyadev/MudaeFarm#127] opened 2020-05-29 12:26 UTC
Is there any possibility to make the bot claim waifus/husbandos based on their value?

For example:
If kakera value >400 the bot will try to claim
If its <400 then the bot will ignore as usual

Or is there some quick way to add top waifus to wished characters?

**Comment by phosphene47** [comment] 2020-05-31 23:41
This is a duplicate of https://github.com/chiyadev/MudaeFarm/issues/38. No progress as of yet.

**Closed by phosphene47** 2020-05-31 23:41 UTC
Labels: enhancement
