### ISSUE TITLE
Wishlist user not working

### ISSUE THREAD

**Issue by Kanokomaro** [chiyadev/MudaeFarm#216] opened 2020-09-20 00:19 UTC
I put my id in the wishlist user channel so that he could claim my wish, my wishlist is public, but even so he didn't claim it, I tried to delete it from the channel and put it again and again he didn't claim it, I didn't click it at the moment it appeared on the bot, but I wish went to Mai Sakurajima.

![Screenshot_6](https://user-images.githubusercontent.com/71573625/93691599-ac051a80-fabd-11ea-9316-1129f1952f0a.png)
![image](https://user-images.githubusercontent.com/71573625/93691606-bf17ea80-fabd-11ea-9218-c9475e891e8d.png)

**Comment by KaiUchiha** [comment] 2020-09-20 16:03
It's a claiming bug. Or, you didn't wish her character in the wished-characters channel. I found that wished-characters works better than account IDs.

**Comment by phosphene47** [comment] 2020-09-22 04:20
Duplicate of https://github.com/chiyadev/MudaeFarm/issues/151. Wishlist based on user IDs had been broken sinxe a long time ago but I haven't had the time to fix it yet. I should pin the issue to prevent more confusion.

**Closed by phosphene47** 2020-09-22 04:20 UTC
