### ISSUE TITLE
Doesn't pick up characters when claim rank and kakera value is enabled?

### ISSUE THREAD

**Issue by bruh8293** [chiyadev/MudaeFarm#206] opened 2020-08-25 23:32 UTC
Is this how the bot works? It works in one server without those values but in one with those values it doesn't.

**Comment by phosphene47** [comment] 2020-08-26 00:41
Sounds like a duplicate of https://github.com/chiyadev/MudaeFarm/issues/182.

**Closed by phosphene47** 2020-08-26 00:41 UTC
