### ISSUE TITLE
Enhancement: Notify /dm you when wished character is rolled instead of autoclaim

### ISSUE THREAD

**Issue by joshoea** [chiyadev/MudaeFarm#179] opened 2020-06-28 22:58 UTC
People in my server are doubting me and think something is wrong whenever I claim a top 100 waifu (all top 100 waifus in my wishlist) especially when its someone elses roll all the time before they do. I think there should be a way when some people in wishlist are rolled that it notifies you instead of claiming. You might wonder doesn't rolling wishlist ping you? but theres a limit of how much ppl in your actual wishlist. You also might suggest having a claim delay but I dont think that will work well.

**Comment by phosphene47** [comment] 2020-06-30 07:33
Duplicate of #148.

**Closed by phosphene47** 2020-06-30 07:33 UTC

**Comment by joshoea** [comment] 2020-06-30 08:22
No I never mentioned windows notification, which made u close it. I mean DM on Discord. That should make things different right?

**Comment by phosphene47** [comment] 2020-06-30 08:43
And how would you DM yourself on Discord?
