### ISSUE TITLE
channel bot response on multiple servers

### ISSUE THREAD

**Issue by KuroizakiKun** [chiyadev/MudaeFarm#147] opened 2020-06-02 16:37 UTC
farm bot does not detect servers other than the server (Seeep / Zeeeblogi Science オ リ ジ ナ ル)
here I use bot for 4 servers but only respond to 1 server after I try to restart

in the first log the log file named (log_2020-06-02 22.30.49Z-20200602) still responds on 4 servers, but suddenly it stops and only responds to 1 server
I'm sorry if my English is bad, I use Google Translate

![log](https://user-images.githubusercontent.com/38588879/83545804-eefcab80-a529-11ea-812f-5068c8323987.png)
[log_2020-06-02 23.09.26Z-20200602.txt](https://github.com/chiyadev/MudaeFarm/files/4718486/log_2020-06-02.23.09.26Z-20200602.txt)
[log_2020-06-02 22.51.27Z-20200602.txt](https://github.com/chiyadev/MudaeFarm/files/4718488/log_2020-06-02.22.51.27Z-20200602.txt)
[log_2020-06-02 22.30.49Z-20200602.txt](https://github.com/chiyadev/MudaeFarm/files/4718489/log_2020-06-02.22.30.49Z-20200602.txt)
[log_2020-06-02 23.21.47Z-20200602.txt](https://github.com/chiyadev/MudaeFarm/files/4718490/log_2020-06-02.23.21.47Z-20200602.txt)
[log_2020-06-02 23.13.01Z-20200602.txt](https://github.com/chiyadev/MudaeFarm/files/4718491/log_2020-06-02.23.13.01Z-20200602.txt)

**Comment by phosphene47** [comment] 2020-06-16 22:38
Can you check #152? I think it seems to be the same issue.

**Comment by phosphene47** [comment] 2020-06-25 09:11
Assuming it is a duplicate of #152, there is a workaround in the comments, so closing.

**Closed by phosphene47** 2020-06-25 09:11 UTC
Labels: bug
